name: Steuerkanzlei König
favicon: null
layout_spectrum: 0.2307
typography_spectrum: 0.51988
title: Steuerkanzlei König
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose:
  - name: awareness
    item: ecd569d5-3030-4edd-93b2-70e097ecd826
    url: null
