name: Steuerkanzlei König
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a8fd9'
    - '#4d4d4d'
    - '#0d376c'
    - '#b2b2b2'
  brandStrength: 0.5
  lightness: null
  saturation: null
  rhythmicContrast: null
purpose: []
